### ISSUE TITLE
How To Use ScrollView in Card?

### ISSUE THREAD

**Issue by vuciv** [alexbrillant/react-native-deck-swiper#351]
I've read through the past problems on this, but can't find a solution that doesn't make the gesture very buggy.

Any thoughts?

**Comment by ksielyov** [comment]
same

**Comment by ithebk** [comment]
verticalSwipe={false}
 
<ScrollView>
 <TouchableWithoutFeedback>
---
</TouchableWithoutFeedback>
</ScrollView>

**Comment by AnatuGreen** [comment]
> verticalSwipe={false}
> 
> And use TouchableWithoutFeedback inside Scrollview

After hours of search, this worked. Some other people recommended using </TouchableOpacity> inside <ScrollView> and I don't know why it did not work for me. This your solution worked perfecto!

**Comment by sametcl2** [comment]
> verticalSwipe={false}
> 
> And use TouchableWithoutFeedback inside Scrollview

Wow! This really saved my day. Thanks.

**Comment by liverpool09** [comment]
> 

This wasted my day. Thanks

**Comment by keranrong** [comment]
Sorry a newbie here. Can someone show me some example code please?

**Comment by willie-hung** [comment]
This worked, thanks!

**Comment by niki-bri** [comment]
Hi, this works like a charm. However, scrolling vertically is freakishly difficult for me as the horizontal swipe gestures are very sensitive. Is there any way to make vertical scrolling less difficult?

**Comment by niki-bri** [comment]
Ok, I fixed it using a touchable opacity. No idea why using TouchableWithoutFeedback did not work for me.

**Comment by cagrigit-hub** [comment]
Hey guys, this solution works on IOS but not on android for me. Any suggestion ?

**Comment by ArnabChatterjee20k** [comment]
```
<ScrollView className="max-h-[150px]" persistentScrollbar={true}>
        <TouchableOpacity
          accessibilityRole="scrollbar"
          onPress={() => alert("hello")}
        >
          <Text className="text-[#E2D8CC] text-xl">{answer}</Text>
        </TouchableOpacity>
      </ScrollView>
```
where am I going wrong ? I tested with touchablewithout feedback as well but not working

**Comment by DaliaaDawod** [comment]
I still have the same problem, anyone solved it?
did not work with TouchableOpacity or with touchableWithoutFeedback

**Comment by danielsilvajobs** [comment]
Sam IOS is fie but not on Android, any solution?

**Comment by EugeneChernov3d** [comment]
Worked for me.
```
<ScrollView >
   <Pressable>
      {content}
   </Pressable>
</ScrollView>
```
